### ISSUE TITLE
Same trend in the same timespan

### ISSUE THREAD

**Issue by afergadis** [afergadis/twitter-bursting-topics-n-fake-news#1]
Why some trends appear >1 times in the same timespan?
 
2	#PAKvSL 	100328
2	#PAKvSL	95175
3	#UbiE3	13496
3	#UbiE3	11445
4	#UbiE3	177384
4	#UbiE3	174422

And what do we do with them?

**Comment by kzama** [comment]
What if we take the average as the total number of each trend, in such situations?
