### ISSUE TITLE
Trends that "skip" timespans

### ISSUE THREAD

**Issue by afergadis** [afergadis/twitter-bursting-topics-n-fake-news#3]
How to we tread trends that "skip" some time spans?

6	#UbiE3	204417
8	#UbiE3	257200

**Comment by kzama** [comment]
In my opinion, we should not take into consideration the "skip" in the computation of "bursting". We can compare a coming trend to a previous one (i.e a previous trend with the same name) , by taking into account the last time the respective trend appeared again -no matter whether the two time spans are in row or not.

Even if a trend is not appeared in the top-10 list of topics at a time span, it doesn't mean that it not famous. Probably it is not popular enough in the specific time span. Suppose that we are in timespan 8 and we have the trends below:
_5 #UbiE3 205517_
_6 #UbiE3 204417_
_8 #UbiE3 257200_

In my opinion,  we should check  whether the #UbiE3 is a bursting topic by comparing it to the respective trend at time span 6.
