### ISSUE TITLE
Which tweets should we return?

### ISSUE THREAD

**Issue by kzama** [afergadis/twitter-bursting-topics-n-fake-news#5]
Suppose that the user chooses to see all the bursting trends of the day. Then it chooses a specific one in order to get more information about it, as well as some tweets based on that trend. 

Which tweets should we return? Two options:

1. The 20 most recent tweets of the specific trend now, (i.e exactly the time that the user asked to see the information).
2. The 20 most recent tweets of the specific trend the time where the trend became "bursting". This means that every time (every 2 hours) we get a set of trends, for each trend we request for the 20 most recent tweets and we store them in a db.table where the _foreign key_ of a record is the _id_ of the trend-of-the-timespan.

**Comment by afergadis** [comment]
Due to time limit and complexity, we choose the last 20 tweets using as a keyword the name of the selected Trend.
